name: inversion_ideas
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  # Requirements
  - numpy>=2.0.0
  - scipy
  - rich
  - simpeg==0.25
  - pymatsolver==0.4.0
  - discretize==0.12.0
  # Required by notebooks
  - harmonica
  - verde
  - pandas
  # Jupyter
  - jupyter
  # Dev
  - pytest
  - ruff
  - mypy
  - scipy-stubs
